repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      require_serial: true
      types_or: [cython, pyi, python]
      args: ["--filter-files"]
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      types: [python]
      require_serial: true
      args:
        - -l
        - "119"
  - repo: https://gitlab.com/pycqa/flake8
    rev: 6de8252c035844f1e679f509b5f37340b44d5c39
    hooks:
    - id: flake8
